### ISSUE TITLE
doesn't create migration 

### ISSUE THREAD

**Issue by ksaadDE** [moigagoo/norman#10]
When I am running 
`norman model -n user`

it just shows
`src/foo/models/user.nim`
but no migration is created.

Idk  what's wrong - no errors or other output :/

**Comment by moigagoo** [comment]
To create a migration for the new model, run `norman generate -i user`.

**Comment by ksaadDE** [comment]
> To create a migration for the new model, run `norman generate -i user`.

Hi, sorry for late reply. Thank you very much for replying that fast!  I will test.
