### ISSUE TITLE
Migration failed with tutorial

### ISSUE THREAD

**Issue by EchoPouet** [moigagoo/norman#7]
Hello,

I would like try your tool but I have a fail during migration. I follow your tutorial and I have this message:
```
norman migrate
Compiled migrations: 1/1.
Failed:
        1593208168_init_db
```

I use Nim 1.2.2 in Ubuntu 18.04 64bits and sqlite is installed.

Thanks.

**Comment by moigagoo** [comment]
I've rewritten Norman from scratch, so this issue is probably not relevant anymore.
